version: "3.7"

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    depends_on:
      - php
    ports:
      - "${NGINX_PORT}:80"
    environment:
      - NGINX_PORT=${NGINX_PORT}
      - NGINX_PHP_CONTAINER=${NGINX_PHP_CONTAINER}
    volumes:
      - .:/var/www/html/:ro
      - ./.docker/config/site.conf:/etc/nginx/conf.d/default.conf
  php:
    container_name: php
    build:
      dockerfile: ./.docker/php/Dockerfile
      context: .
        USER_ID: ${USER_ID}
    volumes:
      - .:/var/www/html/:ro
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini